### ISSUE TITLE
import.meta.glob when starting the server with bun

### ISSUE THREAD

**Issue by m4nuC** [honojs/honox#129]
### What version of HonoX are you using?

0.14

### What steps can reproduce the bug?

I am cloning the basic example from that repo https://github.com/yusukebe/honox-examples/tree/main
when I run the server I am getting the following error:
```
bun-1  | 3 |   const newOptions = {
bun-1  | 4 |     root: options?.root ?? "/app/routes",
bun-1  | 5 |     app: options?.app,
bun-1  | 6 |     init: options?.init,
bun-1  | 7 |     trailingSlash: options?.trailingSlash,
bun-1  | 8 |     NOT_FOUND: options?.NOT_FOUND ?? import.meta.glob("/app/routes/**/_404.(ts|tsx)", {
bun-1  |                                          ^
bun-1  | TypeError: import.meta.glob is not a function. (In 'import.meta.glob("/app/routes/**/_404.(ts|tsx)", {
bun-1  |       eager: !0
bun-1  |     })', 'import.meta.glob' is undefined)
bun-1  |       at createApp (/app/node_modules/honox/dist/server/with-defaults.js:8:38)
bun-1  |       at /app/app/server.ts:4:13
bun-1  | 3 |   const newOptions = {
bun-1  | 4 |     root: options?.root ?? "/app/routes",
bun-1  | 5 |     app: options?.app,
bun-1  | 6 |     init: options?.init,
bun-1  | 7 |     trailingSlash: options?.trailingSlash,
bun-1  | 8 |     NOT_FOUND: options?.NOT_FOUND ?? import.meta.glob("/app/routes/**/_404.(ts|tsx)", {
bun-1  |
```

**Comment by yusukebe** [comment]
Hi @m4nuC 

Did you run `bun` command for your HonoX app? It does not support `bun`.

**Comment by m4nuC** [comment]
@yusukebe I did. 
Any plans on supporting it ?

**Comment by yusukebe** [comment]
@m4nuC 

> Any plans on supporting it ?

No. To use `import.meta.glob`, we have to use `vite`.
