### ISSUE TITLE
methodOverride middleware doesn't work

### ISSUE THREAD

**Issue by kristianfreeman** [honojs/honox#135]
### What version of HonoX are you using?

0.1.9

### What steps can reproduce the bug?

When configuring middleware, specifying the `methodOverride` middleware causes an error:

```ts
import { methodOverride } from 'hono/method-override'

import { createRoute } from 'honox/factory'
import app from "../server"

export default createRoute(
  methodOverride({ app }),
)
```

This may be because I'm unclear what `app` instance to pass here. I tried importing from `../server`, but that may be incorrect!

The HTML code I'm using is:

```html
<form action={`/people/${id}`} method="POST">
  <input type="hidden" name="_method" value="DELETE" />
  <input type="hidden" name="id" value={person.id} />
  <button type="submit">Delete user</button>
</form>
```

### What is the expected behavior?

Able to route to the `DELETE` function, defined below:

```ts
export const DELETE = createRoute(async (c) => {
  const id = c.req.param('id')
  await c.get('prisma').person.delete({ where: { id: Number(id) } })
  return c.redirect('/')
})
```

### What do you see instead?

```
  <-- POST /people/2
TypeError: Cannot read properties of undefined (reading 'fetch')
    at methodOverride2 (/Users/kristianfreeman/src/peeps/node_modules/hono/dist/middleware/method-override/index.js:46:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async dispatch (/Users/kristianfreeman/src/peeps/node_modules/hono/dist/compose.js:32:17)
    at async logger2 (/Users/kristianfreeman/src/peeps/node_modules/hono/dist/middleware/logger/index.js:41:5)
    at async dispatch (/Users/kristianfreeman/src/peeps/node_modules/hono/dist/compose.js:32:17)
    at async dispatch (/Users/kristianfreeman/src/peeps/node_modules/hono/dist/compose.js:32:17)
    at async eval (/Users/kristianfreeman/src/peeps/node_modules/hono/dist/hono-base.js:197:25)
    at async getRequestListener.errorHandler.err (file:///Users/kristianfreeman/src/peeps/node_modules/@hono/vite-dev-server/dist/dev-server.js:87:32)
    at async responseViaResponseObject (file:///Users/kristianfreeman/src/peeps/node_modules/@hono/node-server/dist/index.mjs:303:15)
```

**Comment by yusukebe** [comment]
Hi @kristianfreeman 

We can't use the `app` imported from `../server` in the middleware or handler in `/app/routes/*`. Instead, you can make a "base" app and use it.

`/app/server.ts`:

```ts
import { createApp } from 'honox/server'
import { createHono } from 'honox/factory'

export const baseApp = createHono()

const app = createApp({
  app: baseApp
})

export default app
```

`/app/routes/_middleware.ts`:

```ts
import { methodOverride } from 'hono/method-override'
import { createRoute } from 'honox/factory'
import { baseApp } from '../server'

export default createRoute(async (c, next) => {
  const middleware = methodOverride({ app: baseApp })
  return await middleware(c, next)
})
```

Please try it and let me know if it works or not.

**Comment by yusukebe** [comment]
This can be fixed!
